artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/raw_data
  drive_path: "G:/My Drive/data/ct-kidney/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone"
  local_data_file: kidney_dataset

